private
errorStarted
	self error: 'Round has already started'